# docker-compose up
#
version: '3.7'
services:
  web:
    build: .
    volumes:
      - .:/opt/app
    ports:
      - "9595:9595"
    environment:
      - "RACK_ENV=development"
volumes:
  db:
    driver: local
